module.exports = {
  PORT: 5000,
  MONGO_IP: "MONGO_IP" || "mongo",
  MONGO_PORT: 27017,
  MONGO_USER: "mircoHospitality",
  MONGO_PASSWORD: "mircoHospitality",
  MONGO_DB_NAME: "mircoHospitality",
  MONGO_CLUSTER: "cluster0.ao2qrau.mongodb.net",
  NODE_ENV: "development",
  JWT_SECRET: "mh_app_abcdefghijklmnopqrstuvwxyz1234567890",
  SALT_ROUNDS: 10,
  OTP_LENGTH: 5,
  OTP_VERIFY_DURATION: 15,
  EMAIL_OTP_VERIFY_DURATION: 1440,
  OTP_REQUEST_LIMIT_PER_DAY: 3,
  PASSWORD_MIN_LENGTH: 8,
  SMS_SENDING_PHONE_NUMBER: "8801746693552",
  SYSTEM_DEFAULT_EMAIL_ADDRESS: "ripon.solutionspin@gmail.com",
  USER_PROFILE_DOC_S3_BUCKET_URL: "public/users/profile",
  MAX_UPLOAD_SIZE: 5000000,
  APPLICATION_SHORT_NAME: "MH",
  S3_BUCKET_NAME: "mh-user-bucket",
  S3_REGION: "us-east-1",
  S3_SECRET_ACCESS_KEY: "cW5GNghsxdCMTIo04l3EDR5cTH/B26YmEQytBhoW",
  S3_ACCESS_KEY_ID: "AKIARLFYJVFGWIY2KSAQ",
  ADMIN_PUSH_NOTIFICATION_EMAIL: "admin@gmail.com",

};